### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by oleteacher** [netresearch/ckeditor-cowriter#1]
**Describe the bug**
Demo is throwing errors and not working

**To Reproduce**
1. Try the demo

**Screenshots**
![image](https://user-images.githubusercontent.com/26278259/222863593-c1ad8658-9f0a-4823-aa51-77108b80fb36.png)

**Desktop (please complete the following information):**
 - Win 10
 - Edge

**Additional context**
```
plugin.js?t=MAUD:11 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'tabGeneral')
    at plugin.js?t=MAUD:11:37
    at new CKEDITOR.dialog (ckeditor.js:640:331)
    at a.openDialog (ckeditor.js:689:134)
    at CKEDITOR.command.exec (ckeditor.js:684:445)
    at CKEDITOR.command.exec (ckeditor.js:215:215)
    at a.execCommand (ckeditor.js:289:3)
    at CKEDITOR.tools.extend.click (ckeditor.js:708:247)
    at Object.execute (ckeditor.js:709:359)
    at ckeditor.js:710:234
    at ckeditor.js:33:205
```

**Comment by oleteacher** [comment]
After setting up a test on local dev server, same exact errors.

**Comment by ngolatka** [comment]
I can confirm this. When opening [the demo](https://netresearch.github.io/ckeditor-cowriter/) and clicking the "Co-Writer" icon, the above error occurs.

**Comment by olagwin** [comment]
Problem: it happened when the user had english as browser language. With german it worked.

Solution: as this plugin was in alpha-state, multilanguage was not set up properly yet. This is fixed now so that it should work in german and english with translation of the relevant labels.

**Comment by olagwin** [comment]
Hi @oleteacher , the issue should be solved therefore I close the ticket now. If there are still problems with that for you feel free to reopen it or open a new issue if there is something else. 

Thank you for reporting.

**Comment by oleteacher** [comment]
I will try the plugin again later today, thank you!

**Comment by oleteacher** [comment]
Seems to be working now:)

But the only way to set the API key is in head tag like below and it is visible to all:

    <script>
        const OPENAI_KEY = 'sk-xxxxxxxxxxxxxxxxxxxxxxxxxxx'
        const OPENAI_ORG = 'org-02xO4fTJvkmPLB8PrXccHVSN'
    </script>

Also, the output to ckeditor is not broken down into paragraphs. Just a continuous string.

Is working though!

You might want to consider adding the new turbo model as it is much less cost to use.

Cheers
