### ISSUE TITLE
Add advanced option n

### ISSUE THREAD

**Issue by olagwin** [netresearch/ckeditor-cowriter#6]
See https://platform.openai.com/docs/api-reference/completions/create
Would be good if the user can control it in advanced tab.
But as it states in the note, we should take care to not consume too many tokens with that. 

Together with ticket 5 this would be a good new minor version 1.0.0

**Comment by Gitsko** [comment]
- [x]  CodeReview passed
- [x] advanced option n works


Pls release the new version and close this issue.
